import {
  ArrowLeft, ArrowRight, ArrowUpRight, ChartNoAxesColumn, Bell, LogOut, Clock,
  History, CircleCheck, ClipboardCheck, Compass, Download, Mail, Eye, FileText,
  Stethoscope, FolderOpen, MapPin, LayoutGrid, Headphones, Hourglass, Inbox, Info,
  Map, Megaphone, Paperclip, BadgeCheck, Users, User, UserPlus, Phone, Play, Plus,
  Search, Send, ShieldCheck, Store, StickyNote, MessageSquareText, MessageCircle,
  MessageSquare, IdCard, HeartHandshake, PartyPopper, CreditCard, ThumbsUp, Home,
  Accessibility, CircleAlert, AlertTriangle, ChevronDown, ChevronUp, RefreshCw,
  Package, OctagonX, EyeOff, ImagePlus, ALargeSmall, LayoutDashboard, Trash2,
  Pencil, UserCheck, UserX, FilePlus2, Image, Layers, Sparkles, Landmark, Waves,
  FilePenLine, Cross, Baby, ScanText, MapPinHouse, UserCog,
} from 'lucide-react';

const map = {
  accessibility: Accessibility,
  'a-large-small': ALargeSmall,
  'alert-circle': CircleAlert,
  'alert-triangle': AlertTriangle,
  'exclamation-circle': CircleAlert,
  'exclamation-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-right-up': ArrowUpRight,
  'arrow-up-right': ArrowUpRight,
  'arrow-repeat': RefreshCw,
  'bar-chart': ChartNoAxesColumn,
  'bar-chart-line': ChartNoAxesColumn,
  bell: Bell,
  'bell-fill': Bell,
  'layout-dashboard': LayoutDashboard,
  'pencil': Pencil,
  'trash': Trash2,
  'user-check': UserCheck,
  'user-x': UserX,
  'user-cog': UserCog,
  'file-plus': FilePlus2,
  'box-arrow-right': LogOut,
  'box-arrow-up-right': ArrowUpRight,
  'box-seam': Package,
  'chat-dots-fill': MessageCircle,
  'chat-left-text': MessageSquareText,
  'chat-square-text': MessageSquare,
  'check-circle': CircleCheck,
  'check2-circle': CircleCheck,
  'circle-check': CircleCheck,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  clock: Clock,
  'clock-fill': Clock,
  'clock-history': History,
  'clipboard-check': ClipboardCheck,
  compass: Compass,
  camera: ImagePlus,
  'credit-card-2-front': CreditCard,
  download: Download,
  envelope: Mail,
  'envelope-fill': Mail,
  eye: Eye,
  'eye-slash': EyeOff,
  'file-earmark-text': FileText,
  'file-text': FileText,
  'file-earmark-medical': Stethoscope,
  'folder2-open': FolderOpen,
  'geo-alt': MapPin,
  'geo-alt-fill': MapPin,
  'map-pin': MapPin,
  home: Home,
  grid: LayoutGrid,
  'grid-1x2': LayoutGrid,
  'grid-3x3-gap': LayoutGrid,
  'hand-thumbs-up': ThumbsUp,
  headset: Headphones,
  hourglass: Hourglass,
  'hourglass-split': Hourglass,
  inbox: Inbox,
  image: Image,
  'info-circle': Info,
  layers: Layers,
  landmark: Landmark,
  waves: Waves,
  map: Map,
  megaphone: Megaphone,
  paperclip: Paperclip,
  'patch-check': BadgeCheck,
  people: Users,
  users: Users,
  person: User,
  'person-badge': IdCard,
  'person-circle': User,
  'person-heart': HeartHandshake,
  'person-plus': UserPlus,
  'person-vcard': IdCard,
  phone: Phone,
  'phone-fill': Phone,
  telephone: Phone,
  'telephone-fill': Phone,
  play: Play,
  'play-fill': Play,
  plus: Plus,
  'plus-lg': Plus,
  search: Search,
  send: Send,
  'shield-check': ShieldCheck,
  shop: Store,
  sticky: StickyNote,
  'universal-access': Accessibility,
  'universal-access-circle': Accessibility,
  'x-circle': CircleAlert,
  'x-octagon': OctagonX,
  balloon: PartyPopper,
  'house-door': Home,
  'file-pen-line': FilePenLine,
  cross: Cross,
  baby: Baby,
  'id-card': IdCard,
  'scan-text': ScanText,
  store: Store,
  'map-pin-house': MapPinHouse,
};

export default function AppIcon({ name, size = 16, className = '', strokeWidth = 1.7 }) {
  const Icon = map[name] || CircleAlert;
  return <Icon size={size} className={className} strokeWidth={strokeWidth} aria-hidden="true" />;
}